version: '3.8'

services:
  backend:
    image: fishy001/stream-backend:latest
    container_name: stream-backend
    ports:
      - "8086:8086"
    volumes:
      - ${HOST_MEDIA_PATH}:/media
    restart: unless-stopped

  frontend:
    image: fishy001/stream-frontend:latest
    container_name: stream-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped